server:
  port: 8090

spring:
  application:
    name: student-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
    file:
        name: 'C:\HW6\elk\log\student.log'