server:
  port: 8060

spring:
  application:
    name: eclass-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
    file:
        name: 'C:\HW6\elk\log\eclass.log'
